name = "REPLTranscript"
uuid = "e3cf6f4d-9b28-4ea7-9d7d-8f908f8dce64"
authors = ["WooJoongKim0107 <henrikwjkim@gmail.com>"]
version = "0.1.1"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "1.11"
